### ISSUE TITLE
Prevent week navigation arrows from moving

### ISSUE THREAD

**Issue by NielsNegotica** [tomosterlund/qalendar#128]
**Is your feature request related to a problem? Please describe.**
When browsing through weeks in the calendar, the arrows can move from week to week, probably due to the difference in total number of digits of some dates displayed in the window next to the arrows.

For example, 23-1-2023 - 29-1-2023 is longer than 30-1-2023 - 5-2-2023, making the navigational arrows to the left of the box displaying the dates move a bit to the right.

**Describe the solution you'd like**
I'd like the arrows to stay in 1 position, making it easier to click them at the same position consistently.

**Additional context**
Personally I'd recommend using leading zeros, but I could understand if this would be a change not everyone would like. 
Perhaps changing it into a optional prop could give users the choice?

**Comment by tomosterlund** [comment]
@NielsNegotica thanks for opening this issue.

The solution definitely a good idea ✅ This problem has bugged me out a few times as well.

As to how this should be implemented I'll have to research a little. Potentially, the chevron arrows need to go somewhere else, or I need to set a fixed width of the datepicker, that works for all locales. Leadings zeros is unfortunately not really an option, since the format is governed by the user's locale settings, and this is also the wanted behavior.

I'll keep you posted on this.

**Comment by tomosterlund** [comment]
@NielsNegotica I built a fix for this now, setting a `min-width` on the date picker, adjusted for each mode. I will need to test this a bit more thoroughly when I have time again, but if you want to get this fix immediately, you can run `npm i qalendar@2.0.1-beta.1`. If so, please let me know if this fix does it for you.

**Comment by tomosterlund** [comment]
Fixed with v2.1.1

Thanks again 👍
