### ISSUE TITLE
Optional config property - highlightCurrentDay

### ISSUE THREAD

**Issue by jilliandburke** [tomosterlund/qalendar#149]
**Is your feature request related to a problem? Please describe.**
I would like to highlight the current day (particularly in month mode, but good to have for week as well) with a different background color as a quick way to find where the current day lives on the calendar. I can currently do this with some vanilla JS work, but it doesn't feel super nice to use vanilla JS in vue.

**Describe the solution you'd like**
An optional configuration property would be the easiest as a user, but even just a class we could style for the current day would be great.

**Additional context**
An example of what I've manually created in my project with the 26th being the current date:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/14235846/227814571-a441c7ff-0eca-44d6-aea8-b427bc9107a6.png">

**Comment by tomosterlund** [comment]
Thanks for opening this issue. Agreed, this would be a good feature 👍 

Since the month view is going through some changes for the upcoming v3 release, I'd say we could get on this, as soon as those changes are through.

**Comment by jilliandburke** [comment]
Amazing, thank you!

If I may ask - what changes can we look forward to with the V3 release? I've really been enjoying using Qalendar so I'm excited to hear there's more to come!

**Comment by tomosterlund** [comment]
Glad to hear you’re enjoying it!

@loicgeek is rebuilding the mobile month view.

@felix-berlin is working on implementing a11y-standards, and will build a dark mode.

And I’m working on making day boundaries flexible, not limiting a Qalendar-day to stick within the limits of a regular day: https://github.com/tomosterlund/qalendar/issues/117

**Comment by tomosterlund** [comment]
Thanks again for taking the time to open this issue.

Instead of adding a configuration option, I ended up simply adding a highlight for the current day also in month mode. Didn't make sense to me that all modes should highlight the current date except month-mode.

Since I can tell that you've customized the style a fair bit, my tip for you would be to just override `.calendar-month__weekday.is-today` to your taste 😊 This should be available to you with v3.1.0

**Comment by jilliandburke** [comment]
@tomosterlund thanks so much Tom! 😊

**Comment by tomosterlund** [comment]
@jilliandburke just wanted to give you a hint, since it appears from the image above that you've built your own dark mode for the component: you might want to consider pinning your qalendar dependency to 3.1.0, so that you don't receive an automatic update to 3.2.0, where I'll release dark mode as a built in feature. Then you can take your time to see if you want the upgrade

**Comment by jilliandburke** [comment]
@tomosterlund That's very helpful, thanks again! Very glad to hear a native dark mode is coming as well!
