### ISSUE TITLE
Package path ./dist/style.css is not exported from package

### ISSUE THREAD

**Issue by Depuralina** [tomosterlund/qalendar#170]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Context:**

- Version [e.g. v1.0.0]

**Additional context**

**Comment by Depuralina** [comment]
i need help to solve this issue

**Comment by tomosterlund** [comment]
Hi. Please consider always taking the issue template seriously. I love helping people who use this library, but this is hard when I get almost no details about what the problem is.

About importing the styles: try importing it like shown in the documentation

`<style>
    @import "qalendar/dist/style.css";
</style> `

If this does not help you, feel free to open the issue again.
