### ISSUE TITLE
color-scheme: light not working

### ISSUE THREAD

**Issue by show812223** [tomosterlund/qalendar#196]
**Context :**

- Browser : Edge
- Qalendar Version v.3.5.0

**Describe the bug **
I have set my computer to dark mode and I want Qalendar to apply light mode, so I wrote the following code.

```html
<template>
  <v-card min-height="">
    <v-card-title>
      {{ t("eip.uploadedWorkHour") }}
    </v-card-title>
    <v-card-text style="color-scheme: light" >
      <Qalendar  :events="events" :config="config" style="min-height: 600px;" />
    </v-card-text>
  </v-card>
</template>
```

but my Qalendar still dark, Is there an error in my configuration method? Thank you.

**Comment by tomosterlund** [comment]
You're right, this does not work. Thanks for reporting this.

I'll investigate this and will try and release a patch as soon as possible

**Comment by show812223** [comment]
Thank you so much~!

**Comment by jerryq27** [comment]
Just wanted to throw in my two cents, would it make more sense to have this as an option inside `config`? Granted, I haven't reviewed the code and it might be more trouble than it's worth, especially if it breaks backwards compatibility.

I just think that since this is a bug now, it might be a good opportunity to do that, especially cause it feels odd to have this property on a parent style tag. But that's just my opinion, other than that, this calendar has been a pleasure to work with.

**Comment by jfet97** [comment]
I'm facing the same problem too. Probably adding a new field in `config` would be a good idea, because all the other configurations are centralized there.

I'm not a CSS expert, but a friend of mine who is really good at it told me that `color-scheme` cannot be used to force a light or dark theme. You can only use it on embeddable content or if you use system colors. Or if you use container style queries which are now available only on Chrome and for custom properties.

**Comment by kingdomac** [comment]
It is not working on Chrome browser, it works on Edge and Firefox

**Comment by tomosterlund** [comment]
Hi there. Thanks a lot for filling me in on your concerns and ideas. I've dug around and tried to explore a couple of solutions for this. You've convinced me that probably the best way to handle this is 100% programmatically through the config object, in order to allow 100% control for the implementing developer. Unfortunately, this will mean a breaking change, which requires a bit of extra careful planning on my part.

My first idea on how to solve this, would be to change the current mixin:

```scss
@mixin dark-mode {
  @media (prefers-color-scheme: dark) {
    @content;
  }

  [style*="color-scheme: dark"] & {
    @content;
  }
}
```

to somethings like this:

```scss
  .is-dark & {
    @content;
  }
}
```

and then set a wrapping `is-dark` if this is configured by the implementers. Any thoughts on this?

**Comment by georgeVasiliu** [comment]
@tomosterlund  what do you mean by "and then set a wrapping is-dark class if this is configured by the implementers." ? I have also encountered this issue ( project I am doing is based on light-theme without dark-theme at the moment),  and started looking into this issue.

The way I would assume this could be done per what you said would be:

- switching the mixing to dark-mode like you describe;
- adding a new property in the src/typing/config.interface.ts like this:

`config: {
  // ...
  darkModeEnabled: true, // or false to disable dark mode
  // ...
}`

- in the internal components for every place that uses the dark mode, check the value of darkModeEnabled from the config object and conditionally apply the is-dark class based on its value like this:


.calendar-header {
  // Other styles...
  
  @if config.darkModeEnabled {
    @include dark-mode;
  }
}


Is this close to what you were suggesting? The thing that confuses me is the "is-dark" class itself, if I understood correctly, it only checks for the presence of a class named "is-dark" on the parent element, but this would still imply we have to add "is-dark" to whatever component is acting as parent for the Qalendar component. This seems a bit redundant since you also specify in the config if the dark mode is enabled. I am not expert in CSS so if I understood incorrectly, please disregard that and correct me.


Thanks for this awesome library  btw!

**Comment by tomosterlund** [comment]
@georgeVasiliu 

No, you're right. Adding a class _and_ a config option is counterintuitive, and not what I meant either :) I meant adding a class, as an internal means of making this rule possible

```css
.is-dark & {
    @content;
  }
```

**Comment by c-mac88** [comment]
@tomosterlund Really enjoying this library! Any update (or workaround) on getting the light theme to work? Thanks!

**Comment by ibrahimrehman1** [comment]
Hi @tomosterlund Any updates on this?

**Comment by georgeVasiliu** [comment]
Until the issue itself gets resolved, I've tried to manually "hack" some of the CSS and the way I did was really amateurish but for everyone else that can't wait/want to try out this:
- I just went element by element in dev tools in browser to inspect the CSS styling of the elements and their attributes;
- I just override some of the CSS properties in order to make it look as close as possible to the white theme;
- although it does require quite a few bit of overriding, it still seems to look rather okay:

Here is the full CSS list that I use in my component (style scoped) to override the values:
```
.calendar-root-wrapper .calendar-root {
  background: #fff;
  color: #fff;
  border-color: transparent;
}
.calendar-header__period-name {
  color: #000;
}
.calendar-header__mode-picker {
  color: #fff !important;
  background-color: #fff !important;
  text-emphasis-color: #000 !important;
  border: 1px solid #000 !important;
}
.calendar-header__mode-value {
  color: #000 !important;
  background-color: #fff !important;
}
.calendar-header__mode-options {
  color: #fff !important;
  background-color: #fff !important;
}
.calendar-header__mode-option.is-month-mode {
  color: #000 !important;
  background-color: #fff !important;
}
.calendar-header__mode-option.is-week-mode {
  color: #000 !important;
  background-color: #fff !important;
}
.calendar-header__mode-option.is-day-mode {
  color: #000 !important;
  background-color: #fff !important;
}
.calendar-header__chevron-arrows {
  color: #000 !important;
}
.calendar-header {
  background: #fff;
  color: #fff;
}
.week-timeline__day-name {
  color: #000 !important;
}
.week-timeline__date {
  color: #000 !important;
}
.day-timeline__hour {
  color: #000 !important;
}
.date-picker__value-display {
  color: #000 !important;
  background-color: #fff !important;
  text-emphasis-color: #000 !important;
  border: 1px solid #000 !important;
}
.date-picker__value-display-text {
  color: #000 !important;
  border-color: #000 !important;
}
.date-picker__week-picker {
  background-color: #fff !important;
}
.date-picker__week-picker-navigation {
  color: #000 !important;
}
.date-pickerr__day-names.week {
  color: #000 !important;
}
.date-picker__day-names.week {
  color: #000 !important;
}
.date-picker__week-picker.is-in-qalendar {
  color: #000 !important;
}
.calendar-month__day-name {
  color: #000 !important;
}
.calendar-month__day-date {
  color: #000 !important;
}
.calendar-month__weekday-more {
  color: #000 !important;
}
.calendar-month__event-time {
  color: #000 !important;
}
.calendar-month__event-title {
  color: #000 !important;
}

```
Here is a snapshot with how it looks like:

![image](https://github.com/tomosterlund/qalendar/assets/26601265/a41d9ef4-574d-4ab1-8045-7c48c064b46f)


I know it's not a proper solution! Just laying out in case someone else really wants to just see it white, otherwise I would suggest to just wait on the fix.

**Comment by ibrahimrehman1** [comment]
@georgeVasiliu Thanks man!

**Comment by tomosterlund** [comment]
Also feedback from anyone testing the version is highly appreciated. If it did the job for you or not is enough :)

**Comment by lkochniss** [comment]
Heya :) We are using qalendar@3.5.1-beta.0 with enforced light mode and it works like a charm :)

**Comment by tomosterlund** [comment]
Thanks a lot! My manual and automatic tests were all OK too, so this is now available as the `latest` version over at npm.

Thanks to everyone having pitched in with their thoughts and ideas on this. If anyone feels like getting a sleeker API, regulating the theme over configuration, feel free to open a pull request.
