### ISSUE TITLE
An event that lasts more than 24 hours

### ISSUE THREAD

**Issue by MaximSedov** [tomosterlund/qalendar#95]
Hello! I encountered a problem, is it a bug or not?
If the event is longer than a day and has a time, it is displayed **only** in the day of the event start.
This applies to all three display modes.

If there is no time in the date, it is displayed correctly.
Thank you!

**Comment by tomosterlund** [comment]
Hi!

Currently qalendar only allows for either **timed events** `/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}$/` or **full day events** `/^\d{4}-\d{2}-\d{2}$/`, but not a combination of both. I hold it for a reasonable idea, however, to maybe allow for a combination of both. I'll mark this as a feature request, and will add it to the roadmap.

As a temporary solution, my suggestion would be, that you make a clone of your event, and instead of for example:

`{ start: '2022-11-16 08:00', end: '2022-11-18' }`

do it like this:

```
[
  {
    start: '2022-11-16 08:00',
    end: '2022-11-16 23:59'
  },
  {
    start: '2022-11-17',
    end: '2022-11-18',
  }
]
```

**Comment by MaximSedov** [comment]
Okay, thank you!

**Comment by tomosterlund** [comment]
Okay, I managed to roll this out now. If you run `npm i qalendar@1.16.0`, you should then be able to display multiple-day timed events, such as:

```js
{
  start: "2023-01-01 10:00",
  end: "2023-02-10 02:00"
}
```
